version: '2'

services:
  api:
    build: .
    command: npm run dev
    ports:
      - '8000:8000'
    volumes:
      - .:/code
      - /code/node_modules
    links:
      - mongodb
    environment:
      - VIRTUAL_HOST=api.buddy.dev

  mongodb:
    image: mongo
    ports:
      - "27017:27017"
