version: '2'

services:
  api:
    build: .
    command: npm run dev
    depends_on:
      - mongodb
    ports:
      - '8000:8000'
    volumes:
      - "./app:/src/app"
    links:
      - mongodb

  mongodb:
    image: mongo
    ports:
      - "27017:27017"
